services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle-data-service
    image: vehicle-data-service:prod
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      NODE_ENV: production
    networks:
      - vehicle_network
    ports:
      - "3000:3000"

  db:
    image: postgres:15.4-alpine
    container_name: vehicle-db
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/src/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vehicle_network

volumes:
  postgres-data:

networks:
  vehicle_network:
